# This file contains stuff that is used for both production and development
# ** want in every environment **

version: "3.9"

services:
  # Our Postgres database
  db: # The service will be named db.
    image: postgres # The postgres image will be used
    restart: always # Always try to restart if this stops running
    environment: # Provide environment variables
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE} 


  tailwind:
    build:
      context: ./tailwind
      dockerfile: Dockerfile
    tty: true
    restart: always
    volumes:
      - ./tailwind:/src
      - ./assets:/dst
      - ./templates:/templates

